#!/usr/bin/env pwsh
# azd postprovision hook (Windows / pwsh).
#
# Runs automatically after `azd provision`. It provisions the Foundry IQ
# knowledge base, creates the toolbox connection and toolbox, and stores
# TOOLBOX_ENDPOINT so the agent can reach the toolbox — collapsing every manual
# provisioning step into a single `azd provision`.
#
# Wire it up by adding this to the azure.yaml generated by `azd ai agent init`:
#
#   hooks:
#     postprovision:
#       posix:
#         shell: sh
#         run: ./src/<agent-name>/hooks/postprovision.sh
#       windows:
#         shell: pwsh
#         run: ./src/<agent-name>/hooks/postprovision.ps1

$ErrorActionPreference = "Stop"

# PowerShell does not stop on a non-zero exit code from a native command (like
# azd), so check $LASTEXITCODE after each azd call and fail loudly.
function Invoke-Checked {
    param([scriptblock] $Script, [string] $What)
    & $Script
    if ($LASTEXITCODE -ne 0) { throw "$What failed (exit $LASTEXITCODE)." }
}

# Run from the sample directory (the parent of hooks/) so provision_kb.py and
# toolbox.yaml resolve no matter which directory azd invokes the hook from.
Set-Location (Split-Path -Parent $PSScriptRoot)

# AZURE_SEARCH_ENDPOINT is a prerequisite (your existing Azure AI Search service).
if (-not $env:AZURE_SEARCH_ENDPOINT) {
    throw "AZURE_SEARCH_ENDPOINT is not set. Run: azd env set AZURE_SEARCH_ENDPOINT ""https://<your-search>.search.windows.net"""
}

# Derive the Azure OpenAI endpoint from the Foundry project endpoint when unset.
if (-not $env:AZURE_OPENAI_ENDPOINT -and $env:FOUNDRY_PROJECT_ENDPOINT) {
    $env:AZURE_OPENAI_ENDPOINT = ($env:FOUNDRY_PROJECT_ENDPOINT -replace '/api/projects/.*$', '')
}

Write-Host "Provisioning the Foundry IQ knowledge base..."
Invoke-Checked { uv run --frozen --group provisioning python provision_kb.py } "provision_kb.py"   # stores the KB MCP endpoint as KB_MCP_ENDPOINT

$kb = azd env get-value KB_MCP_ENDPOINT
if (-not $kb) { throw "provision_kb.py did not set KB_MCP_ENDPOINT." }

Write-Host "Creating the knowledge-base-mcp connection..."
# --force upserts so the hook is safe to re-run on every azd provision.
Invoke-Checked {
    azd ai connection create knowledge-base-mcp --kind remote-tool --force `
        --target $kb --auth-type agentic-identity `
        --audience https://search.azure.com --metadata "ApiType=Azure"
} "connection create"

Write-Host "Creating the knowledge-base toolbox..."
# Toolbox versions are immutable and 'create' has no upsert flag, so skip it if
# the toolbox already exists (e.g. on a repeat azd provision). 'toolbox show'
# exits 0 when the toolbox exists and non-zero when it does not. azd writes
# diagnostics to stderr, which PowerShell turns into a terminating error under
# "Stop", so run the probe with errors non-terminating and decide on the exit code.
$prevEap = $ErrorActionPreference
$ErrorActionPreference = "Continue"
azd ai toolbox show knowledge-base *> $null
$toolboxExists = ($LASTEXITCODE -eq 0)
$ErrorActionPreference = $prevEap
if ($toolboxExists) {
    Write-Host "Toolbox knowledge-base already exists; skipping create."
}
else {
    # toolbox.yaml references ${KB_MCP_ENDPOINT} for the tool's server_url; resolve
    # it into a temp file so the toolbox points at this deployment's KB endpoint.
    # The temp file must keep a .yaml extension — azd ai toolbox create rejects others.
    $resolved = (Get-Content ./toolbox.yaml -Raw).Replace('${KB_MCP_ENDPOINT}', $kb)
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) "toolbox-$([System.Guid]::NewGuid()).yaml"
    Set-Content -Path $tmp -Value $resolved -NoNewline
    try {
        Invoke-Checked { azd ai toolbox create knowledge-base --from-file $tmp } "toolbox create"
    }
    finally {
        Remove-Item $tmp -ErrorAction SilentlyContinue
    }
}

# The toolbox's unversioned MCP alias is deterministic from the project endpoint.
$proj = (azd env get-value FOUNDRY_PROJECT_ENDPOINT).TrimEnd('/')
$toolbox = "$proj/toolboxes/knowledge-base/mcp?api-version=v1"
Invoke-Checked { azd env set TOOLBOX_ENDPOINT $toolbox } "env set TOOLBOX_ENDPOINT"

Write-Host "Done. TOOLBOX_ENDPOINT = $toolbox"
