#!/usr/bin/env sh
# azd postprovision hook (POSIX / sh).
#
# Runs automatically after `azd provision`. It provisions the Foundry IQ
# knowledge base, creates the toolbox connection and toolbox, and stores
# TOOLBOX_ENDPOINT so the agent can reach the toolbox — collapsing every manual
# provisioning step into a single `azd provision`.
#
# Wire it up by adding this to the azure.yaml generated by `azd ai agent init`:
#
#   hooks:
#     postprovision:
#       posix:
#         shell: sh
#         run: ./src/<agent-name>/hooks/postprovision.sh
#       windows:
#         shell: pwsh
#         run: ./src/<agent-name>/hooks/postprovision.ps1

set -e

# Run from the sample directory (the parent of hooks/) so provision_kb.py and
# toolbox.yaml resolve no matter which directory azd invokes the hook from.
cd "$(CDPATH= cd "$(dirname "$0")/.." && pwd)"

# AZURE_SEARCH_ENDPOINT is a prerequisite (your existing Azure AI Search service).
if [ -z "$AZURE_SEARCH_ENDPOINT" ]; then
  echo "AZURE_SEARCH_ENDPOINT is not set. Run: azd env set AZURE_SEARCH_ENDPOINT \"https://<your-search>.search.windows.net\"" >&2
  exit 1
fi

# Derive the Azure OpenAI endpoint from the Foundry project endpoint when unset.
if [ -z "$AZURE_OPENAI_ENDPOINT" ] && [ -n "$FOUNDRY_PROJECT_ENDPOINT" ]; then
  export AZURE_OPENAI_ENDPOINT="$(printf '%s' "$FOUNDRY_PROJECT_ENDPOINT" | sed -E 's#/api/projects/.*$##')"
fi

echo "Provisioning the Foundry IQ knowledge base..."
uv run --frozen --group provisioning python provision_kb.py   # stores the KB MCP endpoint as KB_MCP_ENDPOINT

KB="$(azd env get-value KB_MCP_ENDPOINT)"
if [ -z "$KB" ]; then
  echo "provision_kb.py did not set KB_MCP_ENDPOINT." >&2
  exit 1
fi

echo "Creating the knowledge-base-mcp connection..."
# --force upserts so the hook is safe to re-run on every azd provision.
azd ai connection create knowledge-base-mcp --kind remote-tool --force \
  --target "$KB" --auth-type agentic-identity \
  --audience https://search.azure.com --metadata "ApiType=Azure"

echo "Creating the knowledge-base toolbox..."
# Toolbox versions are immutable and 'create' has no upsert flag, so skip it if
# the toolbox already exists (e.g. on a repeat azd provision). 'toolbox show'
# exits 0 when the toolbox exists and non-zero when it does not.
if azd ai toolbox show knowledge-base >/dev/null 2>&1; then
  echo "Toolbox knowledge-base already exists; skipping create."
else
  # toolbox.yaml references ${KB_MCP_ENDPOINT} for the tool's server_url; resolve
  # it into a temp file so the toolbox points at this deployment's KB endpoint.
  # The temp file must keep a .yaml extension — azd ai toolbox create rejects others.
  TMPDIR_KB="$(mktemp -d)"
  trap 'rm -rf "$TMPDIR_KB"' EXIT
  TMP="$TMPDIR_KB/toolbox.yaml"
  KB="$KB" awk '{ gsub(/\$\{KB_MCP_ENDPOINT\}/, ENVIRON["KB"]); print }' ./toolbox.yaml > "$TMP"
  azd ai toolbox create knowledge-base --from-file "$TMP"
fi

# The toolbox's unversioned MCP alias is deterministic from the project endpoint.
PROJ="$(azd env get-value FOUNDRY_PROJECT_ENDPOINT | sed 's#/*$##')"
TOOLBOX="$PROJ/toolboxes/knowledge-base/mcp?api-version=v1"
azd env set TOOLBOX_ENDPOINT "$TOOLBOX"

echo "Done. TOOLBOX_ENDPOINT = $TOOLBOX"
